<?php

namespace App\Filament\Resources\Bulletins\Pages;

use App\Filament\Resources\Bulletins\BulletinResource;
use App\Livewire\PrimeTable;
use Filament\Actions\Action;
use Filament\Actions\EditAction;
use Filament\Forms\Components\Checkbox;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Resources\Pages\ViewRecord;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Tabs\Tab;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use function Illuminate\Support\months;

class ViewBulletin extends ViewRecord
{
    use InteractsWithForms;

    protected static string $resource = BulletinResource::class;

    public function getHeaderWidgets(): array
    {
        return [

        ];
    }

    public function form(Schema $schema): Schema
    {
        return $schema->components([
            TextInput::make('annee')
                ->default((int) date('Y'))
                ->numeric(),
            Select::make('mois')
                ->default(date('m'))
                ->options([1=>'1-Janvier',2=>'2-Fevrier',3=>'3-Mars',
                    4=>'4-Avril',5=>'5-Mai',6=>'6-Juin',
                    7=>'7-Juillet',8=>'8-Aôut',9=>'9-Septembre',
                    10=>'10-Octobre',11=>'11-Novembre',12=>'12-Decembre']),
            Tabs::make('tabs')->tabs([
                Tab::make('DSN Mensuelle')->schema([
                    Repeater::make('bulletins')
                        ->columns(5)
                        ->schema([
                            TextInput::make('libele'),
                            TextInput::make('montant')->numeric()
                                ->live()
                                ->afterStateUpdated(fn(Set $set, Get $get, $state) => $set('total', $state * $get['quantite'])),
                            TextInput::make('quantite')->numeric()
                                ->default(1)
                                ->live()
                                ->afterStateUpdated(fn(Set $set, Get $get, $state) => $set('total', $state * $get['montant'])),
                            TextInput::make('total')
                                ->disabled()
                                ->default(0)
                                ->numeric(),
                            Checkbox::make('actif'),
                        ])
                ]),
                Tab::make('DSN Fin de contrat')->schema([]),
                Tab::make('DSN arrêt de travail')->schema([]),
                Tab::make('BPIJ')->schema([]),
                Tab::make("DPAE déclaration d'embauche")->schema([]),
                Tab::make("DSN d'amorçage")->schema([]),
            ])->columnSpan(3)
        ])->columns(3);
    }


    protected function getActions(): array
    {
        $actions = [

            EditAction::make(),
        ];
        array_push($actions, Action::make('moins_15')->label(months(3)->format('%M')));

        collect()->range(1,12)->each(function($item) use (&$actions) {
            $action = Action::make('mois_'.$item)
                ->label(months($item)->locale);
            array_push($actions, $action);

        });

        return $actions;
    }

    protected function getFooterWidgets(): array
    {
        return [
            PrimeTable::class
        ];
    }

    public function getFooterWidgetsColumns(): int|array
    {
        return 1; // TODO: Change the autogenerated stub
    }
}
