<?php

namespace App\Filament\Resources\Contrats\Pages;

use App\Filament\Resources\Contrats\ContratResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Carbon;

class CreateContrat extends CreateRecord
{
    protected static string $resource = ContratResource::class;

    protected function fillForm(): void
    {
        $this->form->fill([
            'employe_id' => request()->get('employe_id'),
            'etablissement_id' => session()->get('etablissement_id')[0],
        ]);
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['date_fin'] = today()->addMonths((int) $data['duree']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
