<?php

namespace App\Models;

use App\Enums\BulletinStatus;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Bulletin extends Model
{
    protected $guarded = [];
    protected $casts = [
        'statut' => BulletinStatus::class,
    ];

    public function contrat(): BelongsTo
    {
        return $this->belongsTo(Contrat::class);
    }

    public function employe(): BelongsTo
    {
        return $this->belongsTo(Employe::class);
    }

    public function registerGlobalScopes($builder)
    {
        if(session()->has('etablissement_id')){
            $builder->where('etablissement_id', '=', session()->get('etablissement_id')[0]);
        }
        return parent::registerGlobalScopes($builder); // TODO: Change the autogenerated stub
    }

    protected static function booted()
    {
        static::saving(function($model){
            $model->etablissement_id = session()->get('etablissement_id')[0];
        });
    }

}
