<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Contrat extends Model
{
    protected $guarded = [];

    public function employe(): BelongsTo {
        return $this->belongsTo(Employe::class);
    }

    public function registerGlobalScopes($builder)
    {
        if(session()->has('etablissement_id')){
            $builder->where('etablissement_id', '=', session()->get('etablissement_id')[0]);
        }
        return parent::registerGlobalScopes($builder); // TODO: Change the autogenerated stub
    }

    public function bulletins(): HasMany
    {
        return $this->hasMany(Bulletin::class);
    }

    public function generate_bulletin(?int $mois = null): bool
    {
        $mois = $mois ?? now()->month;
        if($this->bulletins()->whereMonth('created_at', '=', $mois)->count() > 0){
            return false;
        }

        $this->bulletins()->create([
            'libele' => "Bulletin $mois-". now() ->year." / ".$this->nom .' '.$this->prenoms,
            'employe_id'=> $this->employe->id,
            'contrat_id' => $this->id,
            'status' => 'Pending'
        ]);

        return true;
    }

    protected static function booted()
    {
        static::saving(function($model){
            $model->etablissement_id = session()->get('etablissement_id')[0];
        });
    }


}
