<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Employe extends Model
{
    protected $guarded = [];

    public function etablissement(): BelongsTo
    {
        return $this->belongsTo(Etablissement::class);
    }

    public function contrats(): HasMany
    {
        return $this->hasMany(Contrat::class);
    }

    public function contrat(): HasOne
    {
        return $this->hasMany(Contrat::class)->one();
    }

    public function bulletins(): HasMany
    {
        return $this->hasMany(Bulletin::class);
    }

    public function generate_bulletin(?int $mois = null): bool
    {
        $mois = $mois ?? now()->month;
        if($this->bulletins()->whereMonth('created_at', '=', $mois)->count() > 0){
            return false;
        }

        $this->bulletins()->create([
            'libele' => "Bulletin $mois-". now() ->year." / ".$this->nom .' '.$this->prenoms,
            'employe_id'=> $this->id,
            'contrat_id' => $this->contrat()->first()->id,
            'status' => 'Pending'
        ]);

        return true;
    }

    public function registerGlobalScopes($builder)
    {
        if(session()->has('etablissement_id')){
            $builder->where('etablissement_id', '=', session()->get('etablissement_id')[0]);
        }

        return parent::registerGlobalScopes($builder); // TODO: Change the autogenerated stub
    }

    protected static function booted()
    {
        static::saving(function($model){
            $model->etablissement_id = session()->get('etablissement_id')[0];
        });
    }
}
