<?php

namespace App\Filament\Pages;

use App\Livewire\TypePrimeTable;
use BackedEnum;
use Filament\Pages\Page;
use Filament\Support\Icons\Heroicon;
use UnitEnum;

class DeclarationsScoiale extends Page
{
    protected string $view = 'filament.pages.declarations-scoiale';
    //protected static string | UnitEnum | null $navigationGroup = "Etablissement";
    protected static string | BackedEnum | null $navigationIcon = Heroicon::OutlinedDocumentCurrencyDollar;
    protected static ?int $navigationSort = 40;


    public static function shouldRegisterNavigation(): bool
    {
        return session()->has('etablissement_id');
    }

    protected function getHeaderWidgets(): array
    {
        return [
            TypePrimeTable::class,
        ];
    }

    public function getHeaderWidgetsColumns(): int|array
    {
        return 1; // TODO: Change the autogenerated stub
    }
}
